### ISSUE TITLE
home_dir vs home_directory

### ISSUE THREAD

**Issue by lucs** [raku-community-modules/System-Passwd#1]
./lib/System/Passwd.pm6 Pod (and README.md) says "home_dir", but the method is actually "home_directory". Note also that the "password" method is not mentioned in the docs.

**Comment by jonathanstowe** [comment]
I'll fix the documentation up but I think we probably want to 'kebab' the names (and deprecate the snakey ones,)

**Comment by lucs** [comment]
Yes, kebab would be nice. FWIW, I also prefer the shorter "home-dir".

**Comment by jonathanstowe** [comment]
Yeah I kebabed the names (and marked the snakey ones as deprecated.)
